openapi: 3.0.1
info:
  title: Social Search
  version: OpenAPI3.1.0.3
servers:
- url: https://sandbox-us-api.experian.com/consumerservices/social-search
paths:
  /v1/social-search:
    post:
      tags:
      - Consumer
      summary: Social Search
      description: 'Retrieves Social Search Report.<br><br>We are providing non-executable "Request schema" which contains all request parameters and executable 10 test cases for client testing under "Examples" dropdown below which includes first 5 positive test cases and rest 5 negative test cases. Eg: Success_1, Failure_Invalid surname etc.'
      operationId: SocialSearch
      parameters:
      - name: clientReferenceId
        in: header
        description: 'API client generated reference Id to uniquely identify the API
          request. '
        schema:
          type: string
          default: SBMYSQL
          enum:
          - SBMYSQL
      - name: Content-Type
        in: header
        description: Input Request format
        required: true
        schema:
          type: string
          default: application/json
          enum:
          - application/json
      - name: Accept
        in: header
        description: Output Response format
        schema:
          type: string
          default: application/json
          enum:
          - application/json
      requestBody:
        description: Consumer's PII , Requestor Information, Addons and any custom
          options to be specified here.
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/socialSearchRequest'
            examples:    # Child of media type
              Request schema:   #Request schema
                value:
                    {
                        "ssn": [
                            {
                                "ssn": "string"
                            }
                        ],
                        "driverslicense": {
                            "number": "string",
                            "state": "string"
                        },
                        "phone": [
                            {
                                "number": "string",
                                "type": "string"
                            }
                        ],
                        "requestor": {
                            "subscriberCode": "string"
                        },
                        "permissiblePurpose": {
                            "type": "string",
                            "terms": "string",
                            "abbreviatedAmount": "string"
                        },
                        "vendorData": {
                            "vendorNumber": "string",
                            "vendorVersion": "string"
                        },
                        "resellerInfo": {
                            "endUserName": "string"
                        },
                        "addOns": {
                            "directCheck": "string",
                            "demographics": "string",
                            "fraudShield": "string"
                        }
                    }
              Success_1:   # Example 1
                value:
                  ssn:
                    - ssn: '111111111'
                  requestor:
                    subscriberCode: '2222222'
                  addOns:
                    directCheck: 'Y'
                    demographics: Geocode and Phone
                    fraudShield: 'Y'
              Success_2:   # Example 2
                value:
                    {
                        "ssn": [
                            {
                                "ssn": "111111111"
                            },
                            {
                                "ssn": "333333333"
                            },
                            {
                                "ssn": "444444444"
                            }
                        ],
                        "requestor": {
                            "subscriberCode": "2222222"
                        },
                        "permissiblePurpose": {
                            "type": "48"
                        },
                        "vendorData": {
                            "vendorNumber": "072",
                            "vendorVersion": "V1.05"
                        },
                        "addOns": {
                            "directCheck": "Y",
                            "demographics": "Geocode and Phone",
                            "fraudShield": "Y"
                        }
                    }
              Success_3:   # Example 3
                value:
                  ssn:
                    - ssn: '111111111'
                    - ssn: '333333333'
                    - ssn: '444444444'
                  driverslicense:
                    number: A352283510
                    state: IL
                  phone:
                    - number: 205-969-1339
                  requestor:
                    subscriberCode: '2222222'
                  permissiblePurpose:
                    type: '48'
                  addOns:
                    directCheck: 'Y'
                    demographics: Geocode and Phone
                    fraudShield: 'Y' 
              Success_4:   # Example 4
                value:
                  ssn:
                    - ssn: '111111111'
                  requestor:
                    subscriberCode: '2222222'
                  permissiblePurpose:
                    type: '48'
                  addOns:
                    directCheck: 'Y'
                    demographics: Geocode and Phone
                    fraudShield: 'Y'
              Success_5:   # Example 5
                value:
                  ssn:
                    - ssn: '111111111'
                    - ssn: '666666666'
                  requestor:
                    subscriberCode: '2222222'
                  permissiblePurpose:
                    type: '48'
                  addOns:
                    directCheck: 'Y'
                    demographics: Geocode and Phone
              Failure_Invalid CurrentAddress:   # Example 6
                value:
                  ssn:
                    - ssn: '111111111'
                  requestor:
                    subscriberCode: '2222222'
                  permissiblePurpose:
                    type: '18'
                    terms: '10'
                    abbreviatedAmount: '10'
                  addOns:
                    directCheck: 'Y'
                    demographics: Geocode and Phone
                    fraudShield: 'N'
                  resellerInfo:
                    endUserName: ABC
              Faiure_Internal System Error For invalid RM- Keyword:   # Example 7
                value:
                  ssn:
                    - ssn: '111111111'
                  requestor:
                    subscriberCode: '2222222'
                  permissiblePurpose:
                    type: '11'
                    terms: '11'
                    abbreviatedAmount: '10'
                  addOns:
                    directCheck: 'Y'
                    fraudShield: 'N'
                  resellerInfo:
                    endUserName: ABC1                                       
              Failure_Inquiry not allowed:   # Example 8
                value:
                  ssn:
                    - ssn: '111111111'
                  requestor:
                    subscriberCode: '2222222'
                  permissiblePurpose:
                    type: '14'
                    terms: '11'
                    abbreviatedAmount: '10'
                  addOns:
                    directCheck: 'Y'
                    fraudShield: 'N'
                  resellerInfo:
                    endUserName: ABC12                                     
              Failure_Internal Error for invalid INQUIRY TYPE keyword:   # Example 9
                value:
                  ssn:
                    - ssn: '111111111'
                  requestor:
                    subscriberCode: '2222222'
                  permissiblePurpose:
                    type: '14'
                    terms: '12'
                    abbreviatedAmount: '10'
                  addOns:
                    directCheck: 'Y'
                    fraudShield: 'N'
                  resellerInfo:
                    endUserName: ABC1232     
              Failure_Invalid surname:   # Example 10
                value:
                  ssn:
                    - ssn: '111111111'
                  requestor:
                    subscriberCode: '2222222'
                  permissiblePurpose:
                    type: '14'
                    terms: '14'
                    abbreviatedAmount: '8'
                  addOns:
                    directCheck: 'Y'
                    fraudShield: 'N'
                  resellerInfo:
                    endUserName: ABC12342                    
        required: true
      responses:
        200:
          description: API responds with a JSON.
          headers:
            experianTransactionId:
              description: Unique ID generated by Experian for this API request
              schema:
                type: string
            clientReferenceId:
              description: Echo back of the reference Id , if provided on API request
                header
              schema:
                type: string
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/socialSearchResponse'
        400:
          description: Client Exception due to invalid data.
          headers:
            experianTransactionId:
              description: Unique ID generated by Experian for this API request
              schema:
                type: string
            clientReferenceId:
              description: Echo back of the reference Id , if provided on API request
                header
              schema:
                type: string
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        403:
          description: Request Forbidden.
          headers:
            experianTransactionId:
              description: Unique ID generated by Experian for this API request
              schema:
                type: string
            clientReferenceId:
              description: Echo back of the reference Id , if provided on API request
                header
              schema:
                type: string
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Not found Data.
          headers:
            experianTransactionId:
              description: Unique ID generated by Experian for this API request
              schema:
                type: string
            clientReferenceId:
              description: Echo back of the reference Id , if provided on API request
                header
              schema:
                type: string
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Server Related Error.
          headers:
            experianTransactionId:
              description: Unique ID generated by Experian for this API request
              schema:
                type: string
            clientReferenceId:
              description: Echo back of the reference Id , if provided on API request
                header
              schema:
                type: string
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        504:
          description: Timeout.
          headers:
            experianTransactionId:
              description: Unique ID generated by Experian for this API request
              schema:
                type: string
            clientReferenceId:
              description: Echo back of the reference Id , if provided on API request
                header
              schema:
                type: string
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
      - OauthSecurity:
        - user
      x-codegen-request-body-name: body
components:
  schemas:
    socialSearchRequest:
      type: object
      properties:
        ssn:
          type: array
          items:
            $ref: '#/components/schemas/SSN'
        driverslicense:
          $ref: '#/components/schemas/DriverLicense'
        phone:
          type: array
          items:
            $ref: '#/components/schemas/Phone'
        requestor:
          $ref: '#/components/schemas/Requestor'
        permissiblePurpose:
          $ref: '#/components/schemas/PermissiblePurpose'
        vendorData:
          $ref: '#/components/schemas/vendorData'
        resellerInfo:
          $ref: '#/components/schemas/Reseller'
        addOns:
          $ref: '#/components/schemas/Addons'
      description: Social Search Request Body
    SSN:
      type: object
      properties:
        ssn:
          type: string
          description: Social Security Number
          default: "999999990"
      description: Consumer's Social Security Number
    Phone:
      type: object
      properties:
        number:
          type: string
          description: Phone Number
          default: 818.555.1111
        type:
          type: string
          description: Phone Type
          default: R
      description: Consumer's Phone
    DriverLicense:
      required:
      - number
      - state
      type: object
      properties:
        number:
          type: string
          description: DL Number
          default: "111111"
        state:
          type: string
          description: State in which DL was issued
          default: CA
      description: Consumer's Driver License
    Requestor:
      required:
      - subscriberCode
      type: object
      properties:
        subscriberCode:
          type: string
          description: Subscriber Number assigned by Experian
          default: "5991764"
      description: Information on the API requestor
    PermissiblePurpose:
      type: object
      properties:
        type:
          type: string
          description: Permissible Purpose Type Code. 2 digits containing the account
            type code only.
          default: "18"
        terms:
          type: string
          description: The Terms must be 3 digits. If unknown             , substitute
            three periods. Mortgage loans use terms expressed in YEARS. Revolving
            accounts use terms expressed as either "001" to indicate a monthly payment
            plan or "010" to indicate a revolving account. All other type codes have
            terms that are expressed in MONTHS
          default: "8"
        abbreviatedAmount:
          type: string
          description: 'Input the amount of the account. Must             be 3 digits.
            If unknown, substitute              three periods. Mortgage loans have
            amounts expressed in THOUSANDS.             For example, a $100,000 VA
            mortgage              for 30 years would be entered as                 "100".
            Under 1000; enter 000. All other type accounts are expressed in HUNDREDS.
            For example, a $15,000 auto loan would be entered as "150". Under 100;
            input 000.    '
          default: "100"
      description: 'Specifies information on why this inquiry is being submitted This
        is used to denote the purpose type, terms, and amount. '
    Reseller:
      type: object
      properties:
        endUserName:
          type: string
          description: End User Identification. Resellers of reports must enter the
            name of the end user upto 30 characters.
          default: ENDUSER
      description: 'If the API requestor is a reseller submitting a inquiry to Experian,
        additional information should be provided.  '
    Addons:
      type: object
      properties:
        directCheck:
          type: string
          description: Send back subscriber information on the report. When set to
            Y indicates that subscriber and court names, addresses, and phone numbers
            who have reported data on the consumer's profile will be sent back on
            the response.
          default: Y
        demographics:
          type: string
          description: Indicates the type of demographic data that should be returned
            back.
        fraudShield:
          type: string
          description: Y - Fraud Shield Product Option will be output
          default: Y
      description: Add on products that can be requested. Each add on is billable.
        These are optional parameters and can be omitted if not needed.
    vendorData:
      type: object
      properties:
        vendorNumber:
          type: string
          description: Optional. Alpha-numeric. Must be 3 Character long.
        vendorVersion:
          type: string
          description: Optional. Alpha-numeric with dot(.). Max length is 6.
      description: Optional field. To understand who's application the client is using
        to send in the inquiry - Vendor, 3rd Party, Reseller, or client home grown.
    socialSearchResponse:
      type: object
      properties:
        socialSearch:
          type: array
          description: Social Search Response
          items:
            $ref: '#/components/schemas/socialSearchResp'
    socialSearchResp:
      type: object
      properties:
        addressInformation:
          type: array
          description: Best Consumer Addresses
          items:
            $ref: '#/components/schemas/addressInformationResp'
        consumerIdentity:
          $ref: '#/components/schemas/consumerIdentity'
        directCheck:
          $ref: '#/components/schemas/directCheck'
        employmentInformation:
          $ref: '#/components/schemas/employmentInformation'
        fraudShield:
          $ref: '#/components/schemas/fraudShield'
        informationalMessage:
          $ref: '#/components/schemas/informationalMessage'
        ssn:
          $ref: '#/components/schemas/ssn'
        statement:
          $ref: '#/components/schemas/statement'
    addressInformationResp:
      type: object
      properties:
        censusGeoCode:
          type: string
          description: Address range that includes the address and the census geography
            the address is within
          default: "4567890"
        city:
          type: string
          description: City for the address.
          default: BURBANK
        countyCode:
          type: string
          description: County Code
          default: "123"
        dwellingType:
          type: string
          description: Structural Characteristic/Dwelling Configuration
        firstReportedDate:
          type: string
          description: 'Date address first reported. Format = MMDDCCYY '
          default: "6011995.0"
        lastReportingSubscriberCode:
          type: string
          description: Last Subscriber reporting this address. May be blanks.
          default: "1220855"
        lastUpdatedDate:
          type: string
          description: 'Date address last updated. Format = MMDDCCYY '
          default: "1011998.0"
        msaCode:
          type: string
          description: Metropolitan Statistical Area Code when DemographicsAll or
            DemographicsGeoCode is requested.
          default: "0"
        source:
          type: string
          description: Source of Address
        state:
          type: string
          description: 'Valid two-letter US state code or Canadian province. '
          default: CA
        stateCode:
          type: string
          description: State Geo Code when demographics = 1 or 2.
          default: "0"
        streetName:
          type: string
          description: 'Full street name. '
          default: BIRCH
        streetPrefix:
          type: string
          description: Data that precedes the street name like house number and directional.
          default: 10655 N
        streetSuffix:
          type: string
          description: Street name type like ST, LN.
          default: ST
        timesReported:
          type: string
          description: Number of times the Address was reported to Experian.
          default: "1"
        unitId:
          type: string
          description: Unit Identifier for Apartment.
          default: ""
        unitType:
          type: string
          description: 'Words such as apartment, suite, etc. '
          default: APT
        zipCode:
          type: string
          description: ZIP Code.
          default: "915021234"
      description: Best Consumer Addresses
    consumerIdentity:
      type: object
      properties:
        dob:
          $ref: '#/components/schemas/dob'
        name:
          $ref: '#/components/schemas/consumerIdentityName'
        phone:
          $ref: '#/components/schemas/consumerIdentityPhone'
        spouseName:
          type: string
          description: When available it will be output.
          default: MARY
    dob:
      type: object
      properties:
        day:
          type: string
          description: When available it will be output in DD format.
          default: "4"
        month:
          type: string
          description: When available it will be output in MM format.
          default: "8.0"
        year:
          type: string
          description: When available it will be output in CCYY format.
          default: "1990"
    consumerIdentityName:
      type: array
      description: Best Consumer Name for Request
      items:
        $ref: '#/components/schemas/consumerIdentityNameResp'
    consumerIdentityNameResp:
      type: object
      properties:
        firstName:
          type: string
          description: Consumer's Full First Name.
          default: JON
        generationCode:
          type: string
          description: Generation Code if applicable.
          default: J
        middleName:
          type: string
          description: Consumer's Full Middle Name or Middle Initial
          default: Q
        secondSurname:
          type: string
          description: Second half of the surname for dual surnames.
          default: CONSUMER
        surname:
          type: string
          description: 'Consumer''s last name. '
          default: CONSUMER
        type:
          type: string
          description: Name Type
          default: A
        confirmedVerifiedSsn:
          $ref: '#/components/schemas/confirmedVerifiedSsn'
    consumerIdentityPhone:
      type: array
      description: Present when DemographicsAll or DemographicsPhone is requested
        on input or via subcode option.
      items:
        $ref: '#/components/schemas/consumerIdentityPhoneResp'
    consumerIdentityPhoneResp:
      type: object
      properties:
        number:
          type: string
          description: 'Consumer Phone Number. '
          default: "5555555555"
        source:
          type: string
          description: Phone Source.
          default: I
        type:
          type: string
          description: Phone number type
          default: ""
    confirmedVerifiedSsn:
      type: array
      description: Consumer's confirmed Verified SSN.
      items:
        $ref: '#/components/schemas/confirmedVerifiedSsnResp'
    confirmedVerifiedSsnResp:
      type: object
      properties:
        timesReportedForSameName:
          type: string
          description: Indicates the number of times this SSN was reported for the
            name
          default: "12"
        ssn:
          type: string
          description: Indicates SSN value in response matched to this Name.
          default: "123456789"
    directCheck:
      type: array
      description: Subscriber Information of subscriber codes shown on report. Present
        when direct check is requested on input or via subcode option.
      items:
        $ref: '#/components/schemas/directCheckResp'
    directCheckResp:
      type: object
      properties:
        subscriberAddress:
          type: string
          description: Subscriber's Address
          default: 10655 N BIRCH ST
        subscriberCity:
          type: string
          description: Subscriber's City
          default: CA
        subscriberCode:
          type: string
          description: Experian assigned number.
          default: "0"
        subscriberName:
          type: string
          description: Name of subscriber
          default: BANK
        subscriberPhone:
          type: string
          description: Telephone number of subscriber or "BYMAILONLY"
          default: BYMAILONLY
        subscriberState:
          type: string
          description: Two-digit state code.
          default: CA
        subscriberZipCode:
          type: string
          description: Subscriber's Zip Code.
          default: "91502"
    employmentInformation:
      type: array
      description: Best Consumer Employments.
      items:
        $ref: '#/components/schemas/employmentInformationResp'
    employmentInformationResp:
      type: object
      properties:
        addressExtraLine:
          type: string
          description: Extra line of employer's address
        addressFirstLine:
          type: string
          description: 1st line of employer's address
          default: 10655 N BIRCH ST
        addressSecondLine:
          type: string
          description: 2nd line of employer's address
          default: WASHINGTON DC
        firstReportedDate:
          type: string
          description: 'Date employment first reported. Format = MMDDCCYY '
          default: "5011991.0"
        lastUpdatedDate:
          type: string
          description: Date employment last updated. Format = MMDDCCYY.
          default: "9011991.0"
        name:
          type: string
          description: Employer's Name.
          default: HARDWARE
        source:
          type: string
          description: Source of Employment
          default: "8"
        zipCode:
          type: string
          description: 'ZIP code of employer. '
          default: "91502"
    fraudShield:
      type: array
      description: Fraud Shield information when requested on input or via subcode.
      items:
        $ref: '#/components/schemas/fraudShieldResp'
    fraudShieldResp:
      type: object
      properties:
        addressCount:
          type: string
          description: Number of times the address was used in the last 90-120 days
          default: "1"
        addressDate:
          type: string
          description: 'Format = MMDDCCYY. Date when address counter accumulation
            started. '
          default: "3011996.0"
        addressErrorCode:
          type: string
          description: Address Error Code if applicable.
          default: "0"
        dateOfBirth:
          type: string
          description: Format = MMDDCCYY
          default: "1101951.0"
        dateOfDeath:
          type: string
          description: Format = MMDDCCYY
          default: "3301996.0"
        fraudShieldIndicators:
          $ref: '#/components/schemas/fraudShieldIndicators'
        sic:
          type: string
          description: Group Identifiers if applicable.
        socialCount:
          type: string
          description: Number of times the social was used in the last 90-120 days.
          default: "1"
        socialDate:
          type: string
          description: 'Date posted when social counter accumulation started. Format
            = MMDDCCYY.  '
          default: "3011996.0"
        socialErrorCode:
          type: string
          description: Social error code if applicable.
        ssnFirstPossibleIssuanceYear:
          type: string
          description: First year possible for SSN issuance (YYYY).
          default: "1965"
        ssnLastPossibleIssuanceYear:
          type: string
          description: Last year possible for SSN issuance (YYYY).
          default: "1966"
        text:
          type: string
          description: Shield message.
        type:
          type: string
          description: Fraud Shield Record Type
          default: "1"
    fraudShieldIndicators:
      type: object
      properties:
        indicator:
          type: array
          description: Fraud Shield Information for the input request.
          items:
            type: string
            default: "5"
      description: Fraud Shield Information for the input request.
    informationalMessage:
      type: array
      description: informational messages for request and response scenarios. e.g.
        if a product option requested is NOT setup for the subcode, response will
        reflect a warning.
      items:
        $ref: '#/components/schemas/informationalMessageResp'
    informationalMessageResp:
      type: object
      properties:
        messageNumber:
          type: string
          description: Contains the last two digits for the message.
          default: "84"
        messageNumberDetailed:
          type: string
          description: The Full Four Digit Number for the message.
          default: "84.0"
        messageText:
          type: string
          description: The message text for the corresponding message number.
          default: PRODUCT OPTION NOT ALLOWED
    ssn:
      type: array
      description: Consumer's profile SSN.
      items:
        $ref: '#/components/schemas/ssnResp'
    ssnResp:
      type: object
      properties:
        number:
          type: string
          description: 'SSN(s) present for the consumer. '
          default: "123456789"
        ssnIndicators:
          type: string
          description: Indicates how the SSN in the response matched to the inquiry
            SSN, digit by digit.
        variationIndicator:
          type: string
          description: 'Indicates if SSN is different than input. '
    statement:
      type: array
      description: Consumer Statements present onfile.
      items:
        $ref: '#/components/schemas/statementResp'
    statementResp:
      type: object
      properties:
        dateReported:
          type: string
          description: Date reported. Format = MMDDCCYY
        statementText:
          type: string
          description: 'Consumer Statement Text. '
        type:
          type: string
          description: '2 character statement type. '
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    Error:
      type: object
      properties:
        message:
          type: string
          description: Client friendly message explaining the error
        errorCode:
          type: string
          description: Experian generated code for this error
      description: Error Response
  securitySchemes:
    OauthSecurity:
      type: oauth2
      flows:
        password:
          tokenUrl: https://sandbox-us-api.experian.com/oauth2/v1/token
          scopes:
            user: user scope
