openapi: 3.0.1
info:
  title: Standalone MLA
  version: OpenAPI3.2.0.1
servers:
- url: https://sandbox-us-api.experian.com/consumerservices/mlastandalone
paths:
  /v2/mlas:
    post:
      tags:
      - Consumer Services
      summary: MLA Standalone
      description: 'Retrieves MLA status of a consumer.<br><br>We are providing non-executable "Request schema" which contains all request parameters and executable 10 test cases for client testing under "Examples" dropdown below which includes first 5 positive test cases and rest 5 negative test cases. Eg: Success_1, Failure_Invalid surname etc.'
      operationId: mlastandalone
      parameters:
      - name: clientReferenceId
        in: header
        description: 'API client generated reference Id to uniquely identify the API
          request.'
        schema:
          type: string
          default: SBMYSQL
          enum:
          - SBMYSQL
      - name: Content-Type
        in: header
        description: Input Request format
        required: true
        schema:
          type: string
          default: application/json
          enum:
          - application/json
      - name: Accept
        in: header
        description: Output Response format
        schema:
          type: string
          default: application/json
          enum:
          - application/json
      requestBody:
        description: Consumer's PII , Requestor Information, Addons and any custom
          options to be specified here.
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/mlaStandaloneRequest'
            examples:
              Request schema:   #Request schema
                value:
                    {
                        "consumerPii": {
                            "primaryApplicant": {
                                "name": {
                                    "lastName": "string",
                                    "firstName": "string",
                                    "middleName": "string",
                                    "generationCode": "Sr"
                                },
                                "dob": {
                                    "dob": "string"
                                },
                                "ssn": {
                                    "ssn": "string"
                                },
                                "driverslicense": {
                                    "number": "string",
                                    "state": "string"
                                },
                                "phone": [
                                    {
                                        "number": "string",
                                        "type": "string"
                                    }
                                ],
                                "employment": {
                                    "employerName": "string",
                                    "employerAddress": {
                                        "line1": "string",
                                        "line2": "string",
                                        "city": "string",
                                        "state": "string",
                                        "zipCode": "string"
                                    }
                                },
                                "currentAddress": {
                                    "line1": "string",
                                    "line2": "string",
                                    "city": "string",
                                    "state": "string",
                                    "zipCode": "string"
                                },
                                "previousAddress": [
                                    {
                                        "line1": "string",
                                        "line2": "string",
                                        "city": "string",
                                        "state": "string",
                                        "zipCode": "string"
                                    }
                                ]
                            }
                        },
                        "requestor": {
                            "subscriberCode": "string"
                        },
                        "permissiblePurpose": {
                            "type": "string",
                            "terms": "string",
                            "abbreviatedAmount": "string"
                        },
                        "resellerInfo": {
                            "endUserName": "string"
                        },
                        "freezeOverride": {
                            "primaryApplFreezeOverrideCode": "string"
                        },
                        "vendorData": {
                            "vendorNumber": "string",
                            "vendorVersion": "string"
                        },
                        "addOns": {
                            "ofacmsg": "string"
                        },
                        "customOptions": {
                            "optionId": [
                                "string"
                            ]
                        }
                    }
              Success_1:   # Example 1
                value:
                    {
                        "consumerPii": {
                            "primaryApplicant": {
                                "name": {
                                    "lastName": "CONNER",
                                    "firstName": "MARIO",
                                    "middleName": "D"
                                },
                                "dob": {
                                    "dob": "1959"
                                },
                                "ssn": {
                                    "ssn": "111111111"
                                },
                                "currentAddress": {
                                    "line1": "1128 ELLEN DR",
                                    "city": "DEER PARK",
                                    "state": "TX",
                                    "zipCode": "77536"
                                }
                            }
                        },
                        "requestor": {
                            "subscriberCode": "2222222"
                        },
                        "permissiblePurpose": {
                            "type": "01"
                        },
                        "resellerInfo": {
                            "endUserName": "TC01A"
                        },
                        "vendorData": {
                            "vendorNumber": "072",
                            "vendorVersion": "V1.05"
                        }
                    } 
              Success_2:   # Example 2
                value:
                  consumerPii:
                    primaryApplicant:
                      name:
                        lastName: RIDER
                        firstName: STEVE
                      dob:
                        dob: '1959'
                      ssn:
                        ssn: '111111111'
                      currentAddress:
                        line1: 45 GREENBRIAR DR
                        city: PITTSBURG
                        state: PA
                        zipCode: '15220'
                  requestor:
                    subscriberCode: '2222222'
                  permissiblePurpose:
                    type: '01'
                  resellerInfo:
                    endUserName: TC41A
                  
              Success_3:   # Example 3
                value:
                  consumerPii:
                    primaryApplicant:
                      name:
                        lastName: BERCE
                        firstName: SYBLEJ
                      dob:
                        dob: '1959'
                      ssn:
                        ssn: '111111111'
                      currentAddress:
                        line1: 5315 GAWAIN APT 423
                        city: SAN ANTONIO
                        state: TX
                        zipCode: '782182131'
                      previousAddress:
                        - line1: PO BOX 484
                          zipCode: '46750'
                          city: HUNTIGTON
                          state: IN
                  requestor:
                    subscriberCode: '2222222'
                  permissiblePurpose:
                    type: '01'
                  resellerInfo:
                    endUserName: TC39A
                  
              Success_4:   # Example 4
                value:
                  consumerPii:
                    primaryApplicant:
                      name:
                        lastName: BOWER
                        firstName: EDDIE
                      dob:
                        dob: '1962'
                      ssn:
                        ssn: '111111111'
                      currentAddress:
                        line1: '124 ORANGE HILL STR #7'
                        city: ORANGE
                        state: CA
                        zipCode: '92869'
                  requestor:
                    subscriberCode: '2222222'
                  permissiblePurpose:
                    type: '04'
                  resellerInfo:
                    endUserName: TC47A
                  
              Success_5:   # Example 5
                value:
                  consumerPii:
                    primaryApplicant:
                      name:
                        lastName: SMITH
                        firstName: SHELDON
                        middleName: STEWART
                      dob:
                        dob: '1959'
                      ssn:
                        ssn: '111111111'
                      currentAddress:
                        line1: 5676 PINE MEADOWS CT
                        city: MORROW
                        state: GA
                        zipCode: 30260-1053
                  requestor:
                    subscriberCode: '2222222'
                  permissiblePurpose:
                    type: '01'
                  resellerInfo:
                    endUserName: TC44A
                  
              Failure_Invalid CurrentAddress:   # Example 6
                value:
                  consumerPii:
                    primaryApplicant:
                      name:
                        lastName: BOLTON
                        firstName: PEGGY
                      dob:
                        dob: '1948'
                      ssn:
                        ssn: '111111111'
                      phone:
                        - type: T
                          number: 555-673-1001
                      currentAddress:
                        line1: ' '
                        city: DECATUR
                        state: GA
                        zipCode: '30033'
                  requestor:
                    subscriberCode: '2222222'
                  permissiblePurpose:
                    type: 3F
                  resellerInfo:
                    endUserName: ABC
                  
              Faiure_Internal System Error For invalid RM- Keyword:   # Example 7
                value:
                  consumerPii:
                    primaryApplicant:
                      name:
                        lastName: COLLINS
                        firstName: DANIEL
                      dob:
                        dob: 04181961
                      ssn:
                        ssn: '111111111'
                      currentAddress:
                        line1: 3064 WOLFE DR
                        line2: ''
                        city: FAIRBORN
                        state: OH
                        zipCode: 45324-2140
                      previousAddress:
                        - line1: 836 WASHINGTON AVE
                          line2: ''
                          city: FAIRBORN
                          state: OH
                          zipCode: '453243840'
                  requestor:
                    subscriberCode: '2222222'
                  permissiblePurpose:
                    type: '18'
                    terms: '010'
                    abbreviatedAmount: '010'
                  addOns: {}
                  resellerInfo:
                    endUserName: ABC1
                                                       
              Failure_Inquiry not allowed:   # Example 8
                value:
                  consumerPii:
                    primaryApplicant:
                      name:
                        lastName: COLLINS
                        firstName: DANIEL
                      dob:
                        dob: 04181961
                      ssn:
                        ssn: '111111111'
                      currentAddress:
                        line1: 3064 WOLFE DR
                        line2: ''
                        city: FAIRBORN
                        state: OH
                        zipCode: 45324-2140
                      previousAddress:
                        - line1: 836 WASHINGTON AVE
                          line2: ''
                          city: FAIRBORN
                          state: OH
                          zipCode: '453243840'
                  requestor:
                    subscriberCode: '2222222'
                  permissiblePurpose:
                    type: '18'
                    terms: '10'
                    abbreviatedAmount: '10'
                  addOns: {}
                  customOptions:
                    optionId:
                      - test
                  resellerInfo:
                    endUserName: ABC2
                                                     
              Failure_Internal Error for invalid INQUIRY TYPE keyword:   # Example 9
                value:
                  consumerPii:
                    primaryApplicant:
                      name:
                        lastName: COLLINS
                        firstName: DANIEL
                      dob:
                        dob: 04181961
                      ssn:
                        ssn: '111111111'
                      currentAddress:
                        line1: 3064 WOLFE DR
                        line2: ''
                        city: FAIRBORN
                        state: OH
                        zipCode: 45324-2140
                      previousAddress:
                        - line1: 836 WASHINGTON AVE
                          line2: ''
                          city: FAIRBORN
                          state: OH
                          zipCode: '453243840'
                  requestor:
                    subscriberCode: '2222222'
                  permissiblePurpose:
                    type: '18'
                    terms: '010'
                    abbreviatedAmount: '010'
                  addOns: {}
                  customOptions:
                    optionId:
                      - test12
                  resellerInfo:
                    endUserName: ABC4
                     
              Failure_Invalid surname:   # Example 10
                value:
                  consumerPii:
                    primaryApplicant:
                      name:
                        lastName: '-'
                        firstName: PEGGY
                      dob:
                        dob: '1948'
                      ssn:
                        ssn: '111111111'
                      phone:
                        - type: T
                          number: 555-673-1001
                      currentAddress:
                        line1: 2965 ATTERBERRY CT
                        city: ' '
                        zipCode: ' '
                  requestor:
                    subscriberCode: '2222222'
                  permissiblePurpose:
                    type: 3F
                  resellerInfo:
                    endUserName: ABC5
                  
        required: true
      responses:
        200:
          description: API responds with a JSON.
          headers:
            experianTransactionId:
              description: Unique ID generated by Experian for this API request
              schema:
                type: string
            clientReferenceId:
              description: Echo back of the reference Id , if provided on API request
                header
              schema:
                type: string
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/mlaStandaloneResponse'
        400:
          description: Client Exception due to invalid data.
          headers:
            experianTransactionId:
              description: Unique ID generated by Experian for this API request
              schema:
                type: string
            clientReferenceId:
              description: Echo back of the reference Id , if provided on API request
                header
              schema:
                type: string
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        403:
          description: Request Forbidden.
          headers:
            experianTransactionId:
              description: Unique ID generated by Experian for this API request
              schema:
                type: string
            clientReferenceId:
              description: Echo back of the reference Id , if provided on API request
                header
              schema:
                type: string
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Not found Data.
          headers:
            experianTransactionId:
              description: Unique ID generated by Experian for this API request
              schema:
                type: string
            clientReferenceId:
              description: Echo back of the reference Id , if provided on API request
                header
              schema:
                type: string
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Server Related Error.
          headers:
            experianTransactionId:
              description: Unique ID generated by Experian for this API request
              schema:
                type: string
            clientReferenceId:
              description: Echo back of the reference Id , if provided on API request
                header
              schema:
                type: string
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        504:
          description: Timeout.
          headers:
            experianTransactionId:
              description: Unique ID generated by Experian for this API request
              schema:
                type: string
            clientReferenceId:
              description: Echo back of the reference Id , if provided on API request
                header
              schema:
                type: string
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
      - OauthSecurity:
        - user
      x-codegen-request-body-name: body
components:
  schemas:
    mlaStandaloneRequest:
      required:
      - consumerPii
      - permissiblePurpose
      - requestor
      type: object
      properties:
        consumerPii:
          $ref: '#/components/schemas/PII'
        requestor:
          $ref: '#/components/schemas/Requestor'
        permissiblePurpose:
          $ref: '#/components/schemas/PermissiblePurpose'
        resellerInfo:
          $ref: '#/components/schemas/Reseller'
        freezeOverride:
          $ref: '#/components/schemas/FreezeOverride'
        vendorData:
          $ref: '#/components/schemas/vendorData'
        addOns:
          $ref: '#/components/schemas/Addons'
        customOptions:
          $ref: '#/components/schemas/CustomOptions'
      description: Request payload to retrieve a MLA Standalone profile
    PII:
      required:
      - primaryApplicant
      type: object
      properties:
        primaryApplicant:
          $ref: '#/components/schemas/PrimaryApplicant'
      description: Personally Identifiable Information
    PAName:
      required:
      - firstName
      - lastName
      type: object
      properties:
        lastName:
          type: string
          description: The full applicant's surname is required. If the surname contains
            two surnames, then split the surnames with a hyphen (e.g., Smith-Jones).
            The surname can also be input with an apostrophe (e.g., O'Brien), although
            apostrophe usage is limited to the letters D, L, and O.
          default: CONSUMER
        firstName:
          type: string
          description: The full first name is required. The minimum entry is the first
            name initial. Blanks and special characters (except dash) are not allowed.
            Compound names should contain a dash (e.g., Billy-Bob).
          default: JOHN
        middleName:
          type: string
          description: The full middle name should be entered when available. A middle
            initial is acceptable. Blanks and special characters are not allowed.
            Omit if the middle name is not available.
          default: QUINCY
        generationCode:
          type: string
          description: Generation Code
          default: Sr
          enum:
          - Jr
          - Sr
          - II
          - III
          - IV
          - V
          - VI
          - VII
          - VIII
          - IX
      description: Consumer's Name
    Address:
      required:
      - line1
      - zipCode
      type: object
      properties:
        line1:
          type: string
          description: Address Line 1
          default: 10655 N BIRCH ST
        line2:
          type: string
          description: Address Line 2
          default: ' '
        city:
          type: string
          description: City
          default: BURBANK
        state:
          type: string
          description: State
          default: CA
        zipCode:
          type: string
          description: ZIP Code
          default: "915021234"
      description: Consumer's Address
    DOB:
      required:
      - dob
      type: object
      properties:
        dob:
          type: string
          description: Year Of Birth or Date of Birth. This describes year of birth
            of the primary applicant. It must be 4 (YYYY) or 8 (MMDDYYYY) digits.
          default: "03021945"
      description: Consumer's Date of Birth
    SSN:
      required:
      - ssn
      type: object
      properties:
        ssn:
          type: string
          description: Social Security Number
          default: "999999990"
      description: Consumer's Social Security Number
    Phone:
      type: object
      properties:
        number:
          type: string
          description: Phone Number
          default: 818.555.1111
        type:
          type: string
          description: Phone Type
          default: R
      description: Consumer's Phone
    Employment:
      required:
      - employerName
      type: object
      properties:
        employerName:
          type: string
          description: Employer's Name
          default: HARDWARE STORE
        employerAddress:
          $ref: '#/components/schemas/Address'
      description: Consumer's Employment Details
    DriverLicense:
      required:
      - number
      - state
      type: object
      properties:
        number:
          type: string
          description: DL Number
          default: "111111"
        state:
          type: string
          description: State in which DL was issued
          default: CA
      description: Consumer's Driver License
    PrimaryApplicant:
      required:
      - currentAddress
      - dob
      - name
      - ssn
      type: object
      properties:
        name:
          $ref: '#/components/schemas/PAName'
        dob:
          $ref: '#/components/schemas/DOB'
        ssn:
          $ref: '#/components/schemas/SSN'
        driverslicense:
          $ref: '#/components/schemas/DriverLicense'
        phone:
          type: array
          items:
            $ref: '#/components/schemas/Phone'
        employment:
          $ref: '#/components/schemas/Employment'
        currentAddress:
          $ref: '#/components/schemas/Address'
        previousAddress:
          type: array
          items:
            $ref: '#/components/schemas/Address'
      description: Primary Credit Applicant Information
    Requestor:
      required:
      - subscriberCode
      type: object
      properties:
        subscriberCode:
          type: string
          description: Subscriber Number assigned by Experian
          default: "5991764"
      description: Information on the API requestor
    PermissiblePurpose:
      required:
      - type
      type: object
      properties:
        type:
          type: string
          description: Permissible Purpose Type Code. 2 digits containing the account
            type code only.
          default: "18"
        terms:
          type: string
          description: The Terms must be 3 digits. If unknown, substitute three periods.
            Mortgage loans will have terms expressed in YEARS. Revolving accounts
            will haveterms expressed as either "001" to indicate a monthly payment
            plan or "010" to indicate a revolving account. All other type codes have
            terms that are expressed in MONTHS.
          default: "8"
        abbreviatedAmount:
          type: string
          description: |-
            Input the amount of the account. Must             be 3 digits. If
             unknown, substitute three periods. Mortgage loans have amounts
             expressed in THOUSANDS. For example, a $100,000 VA mortgage  for 30
             years would be entered as "100". Under 1000; enter 000. All other type
             accounts are expressed in HUNDREDS. For example, a $15,000 auto loan
             would be entered as "150". Under 100; input 000.
          default: "100"
      description: 'Specifies information on why this credit inquiry is being submitted
        This is used to denote the purpose type, terms, and amount. '
    Reseller:
      required:
      - endUserName
      type: object
      properties:
        endUserName:
          type: string
          description: End User Identification. Resellers of credit reports must enter
            the name of the end user upto 30 characters.
          default: ENDUSER
      description: 'If the API requestor is a reseller submitting a credit inquiry
        to Experian, additional information should be provided.  '
    Addons:
      type: object
      properties:
        ofacmsg:
          type: string
          description: Y- Trigger a screening process of taking the consumer data
            from an inquiry to match against the OFAC (Office of Foreign Asset Control)
            and PLC (Palestinian Legislative Council) lists. A message 1202 NAME DOES
            NOT MATCH OFAC/PLC LIST will be printed on credit profile if the consumer
            is not found on either OFAC or PLC list. A message 1200 NAME MATCHES OFAC/PLC
            LIST will be printed on credit profile if the consumer is found on either
            OFAC or PLC list.
          default: Y
      description: Add on products that can be requested. Each add on is billable.
        These are optional parameters and can be omitted if not needed.
    CustomOptions:
      type: object
      properties:
        optionId:
          type: array
          items:
            type: string
            description: Custom option id
      description: Ancillary Credit Reporting Options (Client custom options if any
        that have been setup) that can be requested by client. Multiple options can
        be requested here.
    FreezeOverride:
      type: object
      properties:
        primaryApplFreezeOverrideCode:
          type: string
          description: |-
            This is the freeze override code for the primary applicant
            Used when a consumer has authorized the client to access his or her frozen file and has provided the client with his or her pass code. This passcode is to be provided to Experian so that Experian can override the freeze and return credit data for the consumer back to the client.
      description: If a consumer's profile is frozen, then consumer can get a password
        using which a lender can override the freeze and get credit data. This parameter
        is provided when consumer has provided the lender with the password to override
        his profile freeze.
    vendorData:
      type: object
      properties:
        vendorNumber:
          type: string
          description: Optional. Alpha-numeric. Must be 3 Character long.
        vendorVersion:
          type: string
          description: Optional. Alpha-numeric with dot(.). Max length is 6.
      description: Optional field. To understand who's application the client is using
        to send in the inquiry - Vendor, 3rd Party, Reseller, or client home grown.
    mlaStandaloneResponse:
      type: object
      properties:
        standaloneMLA:
          type: array
          description: MLA Standalone Response
          items:
            $ref: '#/components/schemas/mlaStandaloneResp'
    mlaStandaloneResp:
      type: object
      properties:
        addressInformation:
          type: array
          description: Best Consumer Addresses
          items:
            $ref: '#/components/schemas/addressInformationResp'
        consumerIdentity:
          $ref: '#/components/schemas/consumerIdentity'
        informationalMessage:
          $ref: '#/components/schemas/informationalMessage'
        mla:
          $ref: '#/components/schemas/mlaResp'
        ofac:
          $ref: '#/components/schemas/ofacResp'
        statement:
          $ref: '#/components/schemas/statement'
    addressInformationResp:
      type: object
      properties:
        censusGeoCode:
          type: string
          description: Address range that includes the address and the census geography
            the address is within
          default: "4567890"
        city:
          type: string
          description: City for the address.
          default: BURBANK
        countyCode:
          type: string
          description: County Code
          default: "123"
        dwellingType:
          type: string
          description: Structural Characteristic/Dwelling Configuration
        firstReportedDate:
          type: string
          description: 'Date address first reported. Format = MMDDCCYY '
          default: "6011995.0"
        lastReportingSubscriberCode:
          type: string
          description: Last Subscriber reporting this address. May be blanks.
          default: "1220855"
        lastUpdatedDate:
          type: string
          description: 'Date address last updated. Format = MMDDCCYY '
          default: "1011998.0"
        msaCode:
          type: string
          description: Metropolitan Statistical Area Code when DemographicsAll or
            DemographicsGeoCode is requested.
          default: "0"
        source:
          type: string
          description: Source of Address
        state:
          type: string
          description: 'Valid two-letter US state code or Canadian province. '
          default: CA
        stateCode:
          type: string
          description: State Geo Code when demographics = 1 or 2.
          default: "0"
        streetName:
          type: string
          description: 'Full street name. '
          default: BIRCH
        streetPrefix:
          type: string
          description: Data that precedes the street name like house number and directional.
          default: 10655 N
        streetSuffix:
          type: string
          description: Street name type like ST, LN.
          default: ST
        timesReported:
          type: string
          description: Number of times the Address was reported to Experian.
          default: "1"
        unitId:
          type: string
          description: Unit Identifier for Apartment.
          default: ""
        unitType:
          type: string
          description: 'Words such as apartment, suite, etc. '
          default: APT
        zipCode:
          type: string
          description: ZIP Code.
          default: "915021234"
      description: Best Consumer Addresses
    consumerIdentity:
      type: object
      properties:
        dob:
          $ref: '#/components/schemas/dob'
        name:
          $ref: '#/components/schemas/consumerIdentityName'
        phone:
          $ref: '#/components/schemas/consumerIdentityPhone'
    dob:
      type: object
      properties:
        day:
          type: string
          description: When available it will be output in DD format.
          default: "4"
        month:
          type: string
          description: When available it will be output in MM format.
          default: "8.0"
        year:
          type: string
          description: When available it will be output in CCYY format.
          default: "1990"
    consumerIdentityName:
      type: array
      description: Best Consumer Name for Request
      items:
        $ref: '#/components/schemas/consumerIdentityNameResp'
    consumerIdentityNameResp:
      type: object
      properties:
        firstName:
          type: string
          description: Consumer's Full First Name.
          default: JON
        generationCode:
          type: string
          description: Generation Code if applicable.
          default: J
        middleName:
          type: string
          description: Consumer's Full Middle Name or Middle Initial
          default: Q
        secondSurname:
          type: string
          description: Second half of the surname for dual surnames.
          default: CONSUMER
        surname:
          type: string
          description: 'Consumer''s last name. '
          default: CONSUMER
        type:
          type: string
          description: Name Type
          default: A
    consumerIdentityPhone:
      type: array
      description: Present when DemographicsAll or DemographicsPhone is requested
        on input or via subcode option.
      items:
        $ref: '#/components/schemas/consumerIdentityPhoneResp'
    consumerIdentityPhoneResp:
      type: object
      properties:
        number:
          type: string
          description: 'Consumer Phone Number. '
          default: "5555555555"
        source:
          type: string
          description: Phone Source.
          default: I
        type:
          type: string
          description: Phone number type
          default: ""
    informationalMessage:
      type: array
      description: informational messages for request and response scenarios. e.g.
        if a product option requested is NOT setup for the subcode, response will
        reflect a warning.
      items:
        $ref: '#/components/schemas/informationalMessageResp'
    informationalMessageResp:
      type: object
      properties:
        messageNumber:
          type: string
          description: Contains the last two digits for the message.
          default: "84"
        messageNumberDetailed:
          type: string
          description: The Full Four Digit Number for the message.
          default: "84.0"
        messageText:
          type: string
          description: The message text for the corresponding message number.
          default: PRODUCT OPTION NOT ALLOWED
    mlaResp:
      type: object
      properties:
        messageNumber:
          type: string
          description: Message Number for mla.
          default: ""
        messageText:
          type: string
          description: 'Message Text matching message number is output in this element. '
          default: ""
      description: Present when "mla" is requested on input or via subcode and is
        allowed for the subcode.
    ofacResp:
      type: object
      properties:
        messageNumber:
          type: string
          description: Message Number for ofac.
          default: ""
        messageText:
          type: string
          description: Message Text for corresponding message number.
          default: ""
      description: Present when "ofacmsg" is requested on input or via subcode and
        is allowed for the subcode.
    statement:
      type: array
      description: Consumer Statements present onfile.
      items:
        $ref: '#/components/schemas/statementResp'
    statementResp:
      type: object
      properties:
        dateReported:
          type: string
          description: Date reported. Format = MMDDCCYY
        statementText:
          type: string
          description: 'Consumer Statement Text. '
        type:
          type: string
          description: '2 character statement type. '
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    Error:
      type: object
      properties:
        message:
          type: string
          description: Client friendly message explaining the error
        errorCode:
          type: string
          description: Experian generated code for this error
      description: Error Response
  securitySchemes:
    OauthSecurity:
      type: oauth2
      flows:
        password:
          tokenUrl: https://sandbox-us-api.experian.com/oauth2/v1/token
          scopes:
            user: user scope
